### ISSUE TITLE
TODO-List for "Coding Day" on August, 27 2019

### ISSUE THREAD

**Issue by braunms** [UniStuttgart-VISUS/megamol#390]
Everybody:
- [x]  Create "Priority List" of Renderers and Views (pre-assignment of plugin responsibilities)
- [ ] Build examples for all renderers (project, screenshot, minimal data set) -> in separate example branch

--------------------------------------------

Not Assigned:
- [x] Organising food and drinks (provided by institute? -> ask Karin)
- [ ]  Strategy how to deal with renderers that are too complicated (e.g. remove Renderer and leave remark with last commit)

--------------------------------------------

Tobias:
- [x]  Create template ppt slides (where?)
- [x]  Create coding day branch in master-dev
- [x]  Design "git cycle" for code integration during coding day
- [x] Work flow for reorganising modules (e.g. reduce renderers in core)

--------------------------------------------

Matthias:
- [x]  Prepare VISUS-Pool (20GB local space in C:\temp, VS17, git, cmake, clean keyboards and mice)
- [x]  Example implementation of Renderer (->SphereRenderer) -> Extract Diff to slide

--------------------------------------------

Karsten:
- [ ] Example implementation of View -> Extract Diff to slide
