### ISSUE TITLE
GUI Plugin: Bug and Feature Tracker

### ISSUE THREAD

**Issue by braunms** [UniStuttgart-VISUS/megamol#539]
## Bug
- [ ] Bug - Add alternative hotkey for scrolling (Laptops have no 'middle mouse' button).
- [ ] Bug - Fix varying layout distance between groups for different zoom level.
- [ ] Bug - ImGui: Flickering when vertical and horizontal scrollbars apear at the same time (in a certain way ...)
- [ ] Bug - If mmSetGUIVisible(fals) is called in docked(!) GUI LogConsole window -> mouse interaction is blocked

## Misc

- [ ] Misc - Allow to overwrite existing screenshot files.
- [ ] Misc - Make embedded lua project in screenshot opt-in.
- [ ] Misc - Allow global GUI widgets to be placed in sub-viewport of corresponding view module (e.g. view cube).

## Feature

- [ ] Feature - Sub-groups (groups can contain other groups recursively).
- [ ] Feature - Group multi-selection and combined selection of modules and groups.
- [ ] Feature - Show configurator fullscreen and use global menu bar (mainly to prevent same menu entries twice).
- [ ] Feature - Optimize Performance? (e.g.: directly sync core parameters via core-pointer)
- [ ] Feature - Dialog for screenshots on exit: do you want to provide a more descriptive prefix for these images?
- [ ] Feature - Provenance: Diffs-per-frame-callback. Separate window with parameter history. +back, forward, branching ...
- [ ] Feature - Lua function editor for modifying parameter values.
- [ ] Feature - Keyframe editor / Move cinematic editor to frontend service
- [ ] Feature - Add possibility to load and sync multiple "running" graphs -> project handling
- [ ] Feature - Render output of graph entires in GUI child window.
- [ ] Feature - Add option to return always relative paths for requested files (mainly for file path params).
- [ ] Feature - Save Profiling Bar state to GUI state
- [ ] Feature - Support mltiple compatible calls between modules -> multi-call pop-up
- [ ] Feature - Separate saving of selected group (via context menu)
- [ ] Feature - ClipPlane Manipulation (rename to Plane) (https://github.com/CedricGuillemet/ImGuizmo) - Move on Axes, Rotate, Preview Plane

---

### Pull Request #1111

- [x] Various fixes due to version upgrade of ImGui (see description of PR for more details)

### Pull Request #1005
- [x] Fix - Various fixes for: fixed font size for cinematic stuff, improved UX for scaling and font menu, fixed some stuff in OverlayRenderer, fixed bugs in logconsole auto completion, added File_Any flag to FilePathParam, ModernTrisoupRenderer: fixed mesh color, reset gl state of polygon mode, fixed GUI visibility toggling

### Pull Request #1003
- [x] Fix - Clipping of profiling curve.

### Pull Request #998
- [x] Feature - Added mouse interaction for call curve.

### Pull Request #988
- [x] Feature - Added slider to window menu for transparent GUI window background.

### Pull Request #973
- [x] Misc - Additional call coloring modes for better discriminability of call curves.

### Pull Request #972
- [x] Misc - Improve performance for large log data using imgui clipper.

### Pull Request #970
- [x] Feature - Customizable step size for float and int param widgets (in expert mode).

### Pull Request #926
- [x] Feature - LogConsole extension for executing lua commands as input (+ autocomplete and history)
- [x] Feature - Extension of module and call graph elements to show profiling data

### Pull Request #954
- [x] Feature - Software rendering as alternative render backend 
- [x] Bug - Fixed broken shader pointer of picking
- [x] Bug - Clear fbo if gui is set invisible
- [x] Bug - Increase priority of command service to process only keyboard events not consumed by gui

### Pull Request #872
- [x] Feature - Global Hotkeys and CUE support + GUI hotkey editor window

### Pull Request #879
- [x] Bug - Reset local graph state indicating graph canvas hovering, prevent module pop-up when double-clicked on modules in graph

### Pull Request #877
- [x] Bug - Fixed some param pop-up issues
- [x] Refactor - Rework on external pop-up registration and filepathparam

### Pull Request #874
- [x] Bug - Fix value string in gui param for file paths.

### Pull Request #871 
- [x] Bug - FilePathParam message fix for utf8 and added omitted value to pop-up notification.

### Pull Request #867

- [x] Refactor - Move gui stuff from plugin to frontend service.

### Pull Request #866

- [x] Feature - Prepend module name to interface slot labels. Adjusted interface slot positioning for multiline interface slot labels.

### Pull Request #846
- [x] Refactor - FilePathParam 
  - Internally uses std::filesystem now. This omits operating system dependencies for path format (but keeping interface).
  - Reworked FilePathParam flags -> added tests for flags
  - Added option to allow only specific file extensions for FilePathParam
  - Removed log mesage parsing for notification pop-ups -> moved notification pushes to FilePathParam
- [x] Refactor - Removed useless and expensive UTF8 conversions (FileUtils, GUI, SDFFont)
- [x] Refactor - Global notifications and pop-ups: use weak_ptr for open flag and do not log output when opening pop-up to allow individual log level
- [x] Bug - Fixed OverlayRenderer fbo usage

### Pull Request #812
- [x] Refactor - Major refactoring of how GUI windows are managed 
  - moved all GUI windows to separate classes, reworked window collection
  - removed GUIView and mmconsole support
  - removed support of experimental::filesystem
  - moved RenderUtils and Picking_gl to mmcore::utility

### Pull Request #816
- [x] Bug - Fix significant performance drop for 'large' transfer functions

### Pull Request #809
- [x] Bug - Minor fix of overwriting range behaviour of transfer function.

### Pull Request #806
- [x] Feature - Allow external callback registration for new GUI windows by frontend services.
- [x] Misc - Refactored window configuration.
- [x] Misc - Cleaned header includes.

### Pull Request #804
- [x] Bug - parameter names in GUI graph
- [x] Bug - fixed rendering of calls in configurator
- [x] Bug - minor fix of parameter popup placement in configurator
- [x] Misc - readded checkbox as widget alternative for bool params

### Pull Request #780
- [x] Misc - Transfer Function: 
  - Allow arbitrary range values (so far 'left' range value has to be smaller than 'right' value)
  - Removed condition for transfer function to have always at least two nodes for values 0 and 1
  - Better UX interaction for nodes in transfer function plot 
  - Added option to invert colors of transfer function
- [x] Bug - Fixed linear and gauss interpolation to calculate color value for center of texel
- [x] Feature - Add 'node paint' mode to tf plot - dragging with left mouse button creates new nodes depending on texture size

### Pull Request #770

- [x] Feature - View Cube: Add selection of edges and corners. 
- [x] Feature - View Cube Widget: Added textures for rotation and up arrows
- [x] Misc - Moved relative file names for textures and fonts to global defines in GUIUtils.h
- [x] Misc - Made resource paths globally available in GUIUtils.h
- [x] Misc - Button TF-Editor: Invert Colors

### Pull Request #780
- [x] Feature - Add privacy notice when complete megamol project is stored in EXIF of screenshot
- [x] Feature - Error pop-up when file in file path parameter can not be found (collect all missing files in one pop-up)
- [x] Misc - Some reworking on popup widget functions

### Pull Request #751

- [x] Feature - Toggle running graph from opened graphs in configurator.
- [x] Feature - Flag for call slots (Optional/Required) for colored rendering in GUI graph 
- [x] Misc - Show file path in full width.
- [x] Misc - Disable graph sync when gui is disabled, but still update window data (log, fps)

### Pull Request #761

- [x] Feature - Updated ImGui to version 1.82 (docking branch).
- [x] Feature - Moved cinematic hotkeys to separate ImGui window (using new table feature of imgui).
- [x] Feature - Toggle button for bool parameters.
- [x] Misc - Removed explicit number of segments for circles and round corners, using style.CircleTessellationMaxError instead.

### Pull Request #763

- [x] Feature - Support different mouse cursor shapes for ImGui via GLFW. E.g.: Enables GUI window resize at all four edges.

### Pull Request #759

- [x] Feature - Save/load window docking using ImGui internal ini file settings de-/serialization
- [x] Feature - Added global preset docking space.

### Pull Request #753

- [x] Bug - UX fix: Keep file list in file dialogue widget always at same size independent of log line count.

### Pull Request #722

- [x] Feature - Added GUI state as resource to be available for other frontend services.
- [x] Feature - Made GUI state, GUI visibility and GUI scale available via new LUA commands
- [x] Feature - Load and save GUI state from and to screenshot files.
- [x] Feature - Using project loader service of frontend to load new running project.
- [x] Bug - Performance monitor: Log all values whether performance window is open or not    
- [x] Docu - Minor example name update in megamol docu
- [x] Bug - CinematicView: Fix for new fbo use in views
- [x] Misc - Graph item context menu in regular gui font size.
- [x] Bug - Fixed view cube widget presentation toggle 

### Pull Request #739

- [x] Bug - Fixed loading of projects in configurator
- [x] Bug - Fixed outline drawing of modules in configurator
- [x] Bug - Removed obsolete loading of running project
- [x] Bug - Fixed variable names in verbose mode
- [x] Bug - Fixed graph entry creation for new module
- [x] Bug - Fixed log console log level on forced open
- [x] Bug - Fixed graph state loading in configurator

### Pull Request #732

- [x] Refactoring - Merged 'xxxPresentation' classes. Removed some other 'bad code smells'.
- [x] Bug - Considering new line in log messages.
- [x] Feature - Create graph entry point for new view module when no entry point is already set.

### Pull Request #724

- [x] Bug - Fixed frame drop due to calling expensive Parameter::GetValueString() for each parameter every frame when calling ParameterPresentation::LuaButton().    

### Pull Request #723

- [x] Feature - Rotation of each view cube side in 90 degree steps.
- [x] Refactoring of parameter group classes.

### Pull Request #699

- [x] Cleanup - Merged and unified duplicate utility code (read files, load texture from file, ...).
- [x] Cleanup - Moved file utils to core::utility.
- [x] Cleanup - Refactored OverlayRenderer to use render utils, too.
- [x] Bug - Adapted OverlayRenderer to also work with new megamol frontend.

### Pull Request #712

- [x] Feature - Option to toggle label of calls in configurator (reworked graph menu in configurator).
- [x] Renamed "main view" to more suitable "graph entry".
- [x] Close pop-ups on pressing ESC key.
- [x] Bug - Fixed mouse interaction when GUI is switched to hidden (imgui neesd to frames to update window state).

### Pull Request #709

- [x] Bug - Vector3fParam with GUIPresentation == Direction and init value (x,0,0) shows following behaviour when scrolling while mouse is hovered over the gui element of this ParamSlot: 
    if -1 <= x <= 1, then value gets set to (-1,-0,-0) 
    if x > 1, then value gets set to (-x,-0,-0)
    
### Pull Request #700

- [x] Feature - Hotkey and menu item for enabling/disabling gui.

### Pull Request #697

- [x] Feature - Removed explicit usage of GLFW functions. Using data provided by the glfw service.

### Pull Request #679

- [x] Feature - Groups displayed in the configurator should also group module entries in the GUI.
- [x] Feature - Add button/menu for copying mmSet/mmGetParamValue to clipboard for all parameters (expert mode).
- [x] Bug - Added check for imgui api prerequisities.
- [x] Change - Moved font window to settings menu (slight gui state changes).
- [x] Change - Keeping all windows automatically within current viewport (removed menu for manual reset).
- [x] Feature - Added option for changing global GUI size (e.g. for high DPI displays).
- [x] Bug - Some minor bugs: Relative file paths for VS2019, Module Sidebar/Popup, TF editor, ...
- [x] Feature - Alternative default views (View3D_2) and pickable cube widget.
- [x] Feature - Saving of GUI state is optional via checkbox in file dialog.
- [x] Feature - Platform independent clipboard support using glfw. See issue #695

### Pull Request #670

- [x] Bugs:
  - Fixed state state loading of last project after saving project to new file. 
  - Process only selected/visible graph tab. 
  - Fix hovering for param pop-up when placed on edge. 
  - Propagate tfe Editor window settings stored in state. 
  - Continue project loading on error.
  - Added missing module renaming to queue when project loaded from file.
  - Tfe editor texture size fix for minimized view.
  - Hide external tfe editor in configurator param pop-up
  - Tfe fix overwrite range behaviour
  - Fixed parent root in file browser widget
- [x] Bug - Fix usage of multiple view instances (share font atlas in all ImGui contexts, call creation breaks? ...).
- [x] Feature - Re-enable that always only one main view is active at a time.
- [x] Feature - Consider modules in parameter search, too.
- [x] Bug - Fixed missing new lines for mulit-line parameter values when loading project in configurator from file: Text field in GUI does not keep new lines. Not nice for Lua scripts for the TableManipulator. (in imgui_widgets.cpp only \n is considered) 

### Pull Request #658

- [x] Bug - [megamol] Load module stock (once) before loading project from file via global menu.
- [x] Bug - [megamol] Register changed script path in Lua Service on file drop.
- [x] Bug - Reduced module stock loading time. Loading available modules always at start up now.

### Pull Request #652

- [x] Feature - Upgrade ImGui to version 1.79 and 'docking' branch. Enabled use of window docking.
- [x] Feature - Added log console window options to window configuration for being stored in gui state.
- [x] Bug - Removed megamol module parameters in GUIWindows and replaced with menu options and saving to gui state.
- [x] Bug - Fix docking window background for other color styles.
- [x] Bug - Fix add module to group in configurator for running graph.
- [x] Bug - Fix module param child window and module list child window ordering in configurator for updated imgui 1.79 -> child windows are popups now.

### Pull Request #644

- [x] Bug - Fix call deletion
- [x] Bug - Allow saving and loading of project files without main view.
- [x] Feature - Add slider and drag widgets for float,int,vec2,vec3,vec4 params.
- [x] Feature - Add additional window sizing and positioning options to context menu.

### Pull Request #640

- [x] Feature - Add gui window for log output

### Pull Request #638

- [x] Bug - [megamol] Get script path from new frontend for loading gui state from file.
- [x] Bug - Allow to save running project via configurator.
- [x] Feature - Write gui state json as lua comment at end of project file.
- [x] Feature - [megamol] Add menu for loading projects via gui (hotkey Ctrl+L)
- [x] Feature - [megamol] Add menu for toggling main views (hotkey F5)

### Pull Request #619

- [x] Bug - [megamol] Add warning when GUIView module is used in graph of new frontend. Usage of GUIView module in new frontend graph crashes due to nested ImGuiNewFrame() call -> "Disable" usage of ImGui in GUIView module (+ "unused" label in configurator as explicit hint for user?)
- [x] Feature - [megamol] Add menu option for triggering screenshots in new frontend.
- [x] Feature - Add process for graph synchronisation (for core graph and megamol graph of new fontend).
- [x] Feature - [megamol] Enable renaming of modules/groups for MegaMolgraph  
- [x] Feature - [megamol] Enable creation/deletion of groups for MegaMolgraph  
- [x] Bug - Add interface distinction for the two graphs (MegaMolGraph vs CoreInstanceGraph)
- [x] Feature - [megamol] Enable creation/deletion of main views for MegaMolgraph.
- [x] Bug - Some more UX fixes
- [x] Bug - Folder navigation in file dialog doesn't work if there is an umlaut in the path (but setting path manually will work)
- [x] Bug - Adjust gui and configurator state saving and loading. Adapted to new concept of the running gui graph.
  **Changes:** 
  - Correct saving of states when multiple GUIViews are used, e.g. as main views in two separate windows
  - The configurator state is only stored for the graph running the current project. For all other opened projects in the configurator only the file name of the project is stored. 
  - The project name is stored separately to main view (= view instance) name in graph state.
- [x] Feature - Add possibility to change and save gui parameters for gui being a part of a service in new frontend ->  Saving GUI state to separate file.
- [x] Bug - In a copyied and renamed project file, the graph layout isn't loaded correctly. Looking at the project file it seem the layout is associated with the filename? And also it seems like each time a file is copied and relayouted, a new parameter stack ist added with the new filename
- [ ] Feature - Add relative step size for float and int param widgets (in expert mode)

### Pull Request #618 

- [x] Added graph synchronisation for new megamol graph, see https://github.com/UniStuttgart-VISUS/megamol/tree/frontend_master
- [x] Refactoring: Separated graph classes into own files, consistent log prefix for gui, added graph structure image to readme, 
formatting
- [x] Bug - Some UX fixes

### Pull Request #615

- [x] Bug - Fix 'Del'-Hotkey handling (fix focus handling)
- [x] Bug - Fix position of parameter pop-up window appearing inside graph canvas
- [x] Bug - Fix position of module list window appearing inside graph canvas

### Pull Request #607 
- [x] Feature - Added rotation widget from external project: https://github.com/BrutPitt/imGuIZMO.quat
     (direction of vec3, rotation of vec4 interpreted as quaternion)
- [x] Bug - Fix window positioning 
- [x] Bug - Fix saving of Graph which has been loaded from core

### Pull Request #549
- [x] Separted globally used widgets to own classes (files) and moved widgets to new subfolder.
- [x] Bug- Fix needless interface slot creation on deleting module of group.
- [x] Bug- Fix relative paths ".." from blocking going to parent directory.
- [x] Feature - Added parameter groups for alternative more complex widgets consisting of multiple grouped parameters (via namepace of parameters).
- [x] Some refactoring (Removed namespace configurator, moved and renamed some files, code cleanup).
- [x] Use graph structure of configurator for GUI. Remove CoreInstance dependency (EnumParamters). First version of parameter synchronization between gui and core parameters.
- [x] Refactoring of interface of graph structure classes.
- [x] Merge duplicate parameter widget code (some deeper refactoring of communication between parameters in the core and parameters in the gui)
- [x] Bug - Layouting for loaded files somehow has not right module or call name size. 
- [x]  Saving additional TF editor window option to state (minimized view,vertical view ,active parameter).
- [x] Bug - Allow adding new values for FlexEnums.
- [x] Feature - Add layouting option for modules within a group or just for multi-selected modules.
- [x]  Consider group size when layouting modules.
- [x] Double-click on group header toggles expanded/collapsed view.
- [x] Show connected call slot names at interface slots.
- [x]  Add new modules to group if a) the group is selected when the new module is added via module list sidebar b) the module is added via module list window on double-click and mouse is hovering a group.
- [x] Feature - Separate class for group interface slots for new functionality of custom bundling incoming and outgoing connections for groups.
- [x] Feature - Save and load configurator and graph state (sidebar state, last opened project, etc.)
- [x] Feature - Save parameter GUI options to project file (Read-Only, Visibility, Presentations)
- [x] Feature - Added expert parameter options (Read-Only, Visibility, Presentations) to GUI (added presentation: *Pin Value to Mouse Position*). 
- [x] Improve placement of newly spawned modules.
- [x] Improved drawing order of graph elements.
- [x] Bug - One frame flickering when overlapping graph items are selected.
- [x] Bug - Invert module selection when selected again with shift modifier.
- [x] Bug - Fix selection order for graph items (modules, calls, call slots) overlap.
- [x] Bug - Fix module hover tooltip when modules overlap.
- [x] Bug - Parameter window pinned to module changes height oddly when zooming.

### Pull Request #541
- [x] Bug - Workaround for poor font scaling in ImGui: Load font for configurator in at least two more sizes to switch for different zooming levels.
- [x] Feature - Drag and drop of (project) files from external file browser e.g. (see https://www.glfw.org/docs/latest/input.html#path_drop)
- [x] Feature - Allow selection of multiple modules (e.g. for batch moving of modules). Show all parameters of all selected modules (separated by collapsing header like in GUI parameter window)?
- [x] Feature - Better visual highlighting of current main view (e.g. thicker border). Maybe (disabled) checkbox/button/icon for main view inside all views.
- [x] Feature - Open stock module list only on demand. Via menu, [+] button or inside pop-up at mouse position (e.g. when module search hotkey is pressed or call slot is selected).
- [x] Bug - Selection of wrong graph item is active for one frame until the right selection is propagated.
- [x] Feature - Show parameters of module as pop-up when button/icon inside module is clicked.
- [x] **Major Feature** - Module grouping. (Using already existing namespace in project files for saving module groups defined in configurator.)
- [x] Feature - File Browser: Added 'Directory up' button and added search field for current folder (commit 02da54a, ec95cca)
- [x] Feature - Added FileBrowser button to FilePath parameter widget (commit 02da54a)
- [x] Feature - Load currently running project when configurator is opened the first time (ec95cca)
- [x] Bug - Zooming of font lags one frame behind actual zooming (commit ec95cca)
- [x] Bug - Reset of zooming needs two frames to be applied correct (commit 2b20db2)
- [x] Bug - If parts of the graph are moved out of the lower screen boundary, they won't be rendered properly after zooming out until the view is panned (commit 4f2e4e1)
- [x] Bug - When moving mouse outside canvas while dragging module, dragging break when moving mouse back to canvas (commit 6a724bc)
- [x] Bug - Selected module dragging activates if mouse is outside canvas (commit 6a724bc, 7304260)
- [x] Feature - Enable keyboard navigation (e.g. for module creation: Ctrl+Shift+m / 'sphere' / Down... / Space) NOTE: Navigation is predefined in ImGui => Enable Text Input = Enter, Activate 'Item' = Space (commit ec5d6e9)
- [x] Adjust multiple selection of modules, calls or call slots (commit 5005caf)
- [x] Bug - Adapt transparency and ordering of modules, calls and call slots for less confusion when selecting or hovering  (commit 5005caf)
- [x] Bugs - Missing update for module size when changing tabs. Splitter child window overlap  (commit 5005caf)

### Pull Request #537 (issue #536)
- [x] Bug - Saving project fails when any not default IntParam value was assigned before

### Pull Request #530 
- [x] Feature - First configurator prototype
